### ISSUE TITLE
c0gBbiUZe6k requires login to view

### ISSUE THREAD

**Issue by Morteza820** [JuanBindez/pytubefix#157] opened 2024-08-06 19:57 UTC
i have this error 
c0gBbiUZe6k requires login to view
what to do now?

**Comment by ohs2033** [comment] 2024-08-07 02:16
It still happening in 6.9.2


2024-08-07T02:13:53.803Z | Retry failed [91mozTWlCoI5BE requires login to view[0mTraceback (most recent call last):
-- | --
  | 2024-08-07T02:13:53.803Z | File "/var/task/pytubefix/__main__.py", line 612, in title
  | 2024-08-07T02:13:53.803Z | self._title = self.vid_info['videoDetails']['title']
  | 2024-08-07T02:13:53.803Z | KeyError: 'videoDetails'
  | 2024-08-07T02:13:53.803Z | During handling of the above exception, another exception occurred:
  | 2024-08-07T02:13:53.803Z | Traceback (most recent call last):
  | 2024-08-07T02:13:53.803Z | File "/var/task/handler.py", line 577, in entry
  | 2024-08-07T02:13:53.803Z | title, video_length, description = get_title(
  | 2024-08-07T02:13:53.803Z | File "/var/task/utils/misc.py", line 15, in wrapper
  | 2024-08-07T02:13:53.803Z | return func(*args, **kwargs)
  | 2024-08-07T02:13:53.803Z | File "/var/task/handler.py", line 104, in get_title
  | 2024-08-07T02:13:53.803Z | return yt.title, yt.length, yt.description
  | 2024-08-07T02:13:53.803Z | File "/var/task/pytubefix/__main__.py", line 616, in title

**Comment by danielfabriq** [comment] 2024-08-07 08:25
I am facing similar issue

**Comment by buffalobill571** [comment] 2024-08-07 10:09
Similar issue

**Comment by giklepach** [comment] 2024-08-07 10:09
Same problem

**Comment by ablackoff** [comment] 2024-08-07 10:10
same problem

**Comment by JuanBindez** [comment] 2024-08-07 13:50
```python
yt = YouTube(url, use_oauth=True, allow_oauth_cache=True, on_progress_callback = on_progress)
```

**Comment by robochopbg** [comment] 2024-08-07 14:57
Good day.

I'm also getting this error as the others but the actual error coming from Youtube/Google is

{'responseContext': {'visitorData': 'Cgs4QkpLcTVJOS1OcyjVis61BjIiCgJCRxIcEhgSFgsMDg8QERITFBUWFxgZGhscHR4fICEgXQ%3D%3D', 'maxAgeSeconds': 0}, 'playabilityStatus': {'status': 'LOGIN_REQUIRED', 'reason': 'Sign in to confirm you’re not a bot'}, 'trackingParams': 'CAAQu2kiEwic-IiqjOOHAxWy6UIFHawtCfA=', 'adBreakHeartbeatParams': 'Q0FBJTNE'}

Regards

**Comment by JuanBindez** [comment] 2024-08-07 17:09
what code are you using to test?

**Comment by robochopbg** [comment] 2024-08-07 19:01
I'm using s = Search(query)
then call s.videos
loop over this then call
s.get_next_results()

when all is done and i'm getting video.title from each Youtube object and this when the error happens.

Regards

**Comment by tanzhengyang** [comment] 2024-08-08 06:06
the same problem
  File "/usr/local/lib/python3.10/site-packages/pytubefix/__main__.py", line 616, in title
    self.check_availability()
  File "/usr/local/lib/python3.10/site-packages/pytubefix/__main__.py", line 310, in check_availability
    raise exceptions.LoginRequired(video_id=self.video_id)
pytubefix.exceptions.LoginRequired: M7-h3FO-KKo requires login to view

**Comment by Win-commit** [comment] 2024-08-08 06:55
The same problem 
             (vscode-notebook-cell:?execution_count=7&line=12)
     [10](vscode-notebook-cell:?execution_count=7&line=10) yt = YouTube(data["youtube_url"])
     [11](vscode-notebook-cell:?execution_count=7&line=11) video_id = parse_video_id(data["youtube_url"])
---> [12](vscode-notebook-cell:?execution_count=7&line=12) video_stream = yt.streams.filter(progressive=True, file_extension='mp4', res="360p").first()
     [13](vscode-notebook-cell:?execution_count=7&line=13) save_file = os.path.join('peterVideo', video_id+'.mp4')
     [14](vscode-notebook-cell:?execution_count=7&line=14) video_stream.download(filename=save_file)

File [d:\anaconda3\envs\geo\lib\site-packages\pytubefix\__main__.py:552](file:///D:/anaconda3/envs/geo/lib/site-packages/pytubefix/__main__.py:552), in YouTube.streams(self)
    [546](file:///D:/anaconda3/envs/geo/lib/site-packages/pytubefix/__main__.py:546) @property
    [547](file:///D:/anaconda3/envs/geo/lib/site-packages/pytubefix/__main__.py:547) def streams(self) -> StreamQuery:
    [548](file:///D:/anaconda3/envs/geo/lib/site-packages/pytubefix/__main__.py:548)     """Interface to query both adaptive (DASH) and progressive streams.
    [549](file:///D:/anaconda3/envs/geo/lib/site-packages/pytubefix/__main__.py:549) 
    [550](file:///D:/anaconda3/envs/geo/lib/site-packages/pytubefix/__main__.py:550)     :rtype: :class:`StreamQuery <StreamQuery>`.
    [551](file:///D:/anaconda3/envs/geo/lib/site-packages/pytubefix/__main__.py:551)     """
--> [552](file:///D:/anaconda3/envs/geo/lib/site-packages/pytubefix/__main__.py:552)     self.check_availability()
    [553](file:///D:/anaconda3/envs/geo/lib/site-packages/pytubefix/__main__.py:553)     return StreamQuery(self.fmt_streams)

File [d:\anaconda3\envs\geo\lib\site-packages\pytubefix\__main__.py:310](file:///D:/anaconda3/envs/geo/lib/site-packages/pytubefix/__main__.py:310), in YouTube.check_availability(self)
    [308](file:///D:/anaconda3/envs/geo/lib/site-packages/pytubefix/__main__.py:308)         raise exceptions.AgeRestrictedError(video_id=self.video_id)
    [309](file:///D:/anaconda3/envs/geo/lib/site-packages/pytubefix/__main__.py:309)     else:
--> [310](file:///D:/anaconda3/envs/geo/lib/site-packages/pytubefix/__main__.py:310)         raise exceptions.LoginRequired(video_id=self.video_id)
    [312](file:///D:/anaconda3/envs/geo/lib/site-packages/pytubefix/__main__.py:312) elif status == 'AGE_CHECK_REQUIRED':
    [313](file:///D:/anaconda3/envs/geo/lib/site-packages/pytubefix/__main__.py:313)     if self.use_oauth:

LoginRequired: 1c3XwxTTcgA requires login to view

**Comment by Win-commit** [comment] 2024-08-08 07:05
> ```python
> yt = YouTube(url, use_oauth=True, allow_oauth_cache=True, on_progress_callback = on_progress)
> ```

Yes! it works out on me. It requires you to connect Youtube with Youe google account ,and the problem "requires login to view"  will be fixed

**Comment by robochopbg** [comment] 2024-08-08 07:54
Problem here is when using Search() class the YouTube() class is called internally to create the YouTube objects so then would need to update pytubefix/contrib/search.py module under 
def fetch_and_parse(self, continuation=None):
      # Get videos results
      if 'videoRenderer' in video_details:
           videos.append(YouTube(f"https://www.youtube.com/watch?v={video_details['videoRenderer']['videoId']}"))
           
to use_oauth=True, allow_oauth_cache=True

**Comment by danielfabriq** [comment] 2024-08-08 12:45
> ```python
> yt = YouTube(url, use_oauth=True, allow_oauth_cache=True, on_progress_callback = on_progress)
> ```

Is this the solution? What was the cause of the issue and how does this solution solve it? 
FYI I am running my code on AWS Lambda function

**Comment by robochopbg** [comment] 2024-08-08 14:00
I did try the oauth but haven't tested enough to see if the if I still get login errors.

So this thing with YouTube login to make sure you are not a bot is newish because after writing my app code it's only now in last few days that I got this issue.

After using oauth once then I do need to remove or set oauth back to false otherwise it keeps asking to login with the code.

Now I just need to come up with a more elegant way to handle the oauth prompt in pyside6 app.

**Comment by Mak5er** [comment] 2024-08-08 20:27
I have saame problem but i can ot auth because i use pytube with docker

**Comment by robochopbg** [comment] 2024-08-09 08:13
This issue is still happening even when oauth was used.

{'responseContext': {'visitorData': 'Cgsxc0hqRmVodmJrMCjOnte1BjIiCgJCRxIcEhgSFgsMDg8QERITFBUWFxgZGhscHR4fICEgGw%3D%3D', 'maxAgeSeconds': 0}, 'playabilityStatus': {'status': 'LOGIN_REQUIRED', 'reason': 'Sign in to confirm you’re not a bot'}, 'trackingParams': 'CAAQu2kiEwjH8OmTu-eHAxUy5kIFHVziC_A=', 'adBreakHeartbeatParams': 'Q0FBJTNE'}

**Comment by yannickErp** [comment] 2024-08-09 11:45
Same problem, haven't found a solution yet, I am also running it in a docker container in AWS Lambda....

**Comment by rowlinsonmike** [comment] 2024-08-10 05:17
for those running this on lambda, I got it working by getting token data from google oauth playground
1. Go to the Google OAuth 2.0 Playground (https://developers.google.com/oauthplayground/)
2. On the left side, scroll down and select "YouTube Data API v3" under the YouTube APIs section.
3. Select the scopes you need, "https://www.googleapis.com/auth/youtube.readonly" for read-only access.
4. Click the "Authorize APIs" button.

then create the token file before you instantiate `YouTube`
```python
    data = {
        "access_token": os.getenv("access_token"),
        "refresh_token": os.getenv("refresh_token"),
        "expires": 1823266077 # some number in the future so it doesn't try refreshing the bearer token
    }
    with open("/tmp/token.json", "w") as f: # make sure you write to /tmp for lambda
        json.dump(data, f)
```

then specify the token_file parameter for `YouTube`

```python
yt = YouTube(
        url, use_oauth=True, allow_oauth_cache=True, token_file="/tmp/token.json"
)
```

**Comment by JuanBindez** [comment] 2024-08-11 17:52
take a look at #170

**Closed by JuanBindez** 2024-08-11 17:52 UTC
Labels: bug

**Comment by tanzhengyang** [comment] 2024-08-12 02:49
> YouTube
I used the method you provided, and it prompted 403

**Comment by danielfabriq** [comment] 2024-08-12 14:21
> ```python
> token_file
> ```

Tried out this one and got `HTTP Error 401: Unauthorized`
